### ISSUE TITLE
Adding 1 day to March24th in the Atlantic/Azores timezone yields the same day.

### ISSUE THREAD

**Issue by dmarchin** [moment/moment-timezone#716] opened 2019-01-10 20:09 UTC
**Describe the bug**
Adding 1 day to March24th in the Atlantic/Azores timezone yields the same day.

**To Reproduce**
```
moment.tz.setDefault("Atlantic/Azores");
moment("2018-03-24", "YYYY-MM-DD").add(1, "days").format("YYYY-MM-DD")
"2018-03-24"
```

**Expected behavior**
Moment should correctly display the next day: "2018-03-25"

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Moment-specific environment**
Ran in chrome dev console on https://momentjs.com/
```
moment.tz.setDefault("Atlantic/Azores");
moment("2018-03-24", "YYYY-MM-DD").add(1, "days").format("YYYY-MM-DD")
"2018-03-24"

console.log((new Date()).toString())
console.log((new Date()).toLocaleString())
console.log((new Date()).getTimezoneOffset())
console.log(navigator.userAgent)
console.log(moment.version)
Thu Jan 10 2019 15:02:54 GMT-0500 (Eastern Standard Time)
1/10/2019, 3:02:54 PM
300
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
2.23.0
```

**Comment by mj1856** [comment] 2019-04-16 05:37
Duplicate of #409, just a different time zone that also has midnight transitions. Tracking there. Thanks.

**Closed by mj1856** 2019-04-16 05:37 UTC
