### ISSUE TITLE
Setting default time zone is ignored by moment

### ISSUE THREAD

**Issue by ramik91** [moment/moment-timezone#869] opened 2020-07-08 20:23 UTC
I upgraded moment-timezone to 0.5.31 and moment to 2.27.0 in our React project. Tests started to fail due to issue described below. Is it now necessary to use moment-timezone imports only in order to get timezone aware date object?

### Repro steps:
```javascript
import momentTimezone from 'moment-timezone';
import moment from 'moment';

momentTimezone.tz.setDefault('America/Chicago');

const tzDate = momentTimezone('2019-06-25T12:30:00+00:00');
const date = moment('2019-06-25T12:30:00+00:00');


console.log('tzDate:,' tzDate.format('M/D/YYYY h:mm A'));
console.log('date:', date.format('M/D/YYYY h:mm A'));
```

### Result:
```
tzDate: 6/25/2019 7:30 AM
date: 6/25/2019 12:30 AM
```

### Expected:
```
tzDate: 6/25/2019 7:30 AM
date: 6/25/2019 7:30 AM
```

**Comment by ETSmukesh** [comment] 2020-07-22 07:29
I am also getting my local system timezone after setting another default timezone.

**Comment by gongAll** [comment] 2020-08-12 01:22
Me too. I have traced the error to the moment@2.25.0 version. moment@2.24.0 works just fine.

**Comment by ichernev** [comment] 2022-08-26 13:27
I'm pretty sure this is the same as https://github.com/moment/moment-timezone/issues/892

Closing this in favor of the other one, please check with latest moment/moment-timezone, also I see you're using new js module system (which means there is some compat layer). Try with regular require in a new project (with no other dependencies), if the problem is gone it's likely due to multiple moment versions.

**Closed by ichernev** 2022-08-26 13:27 UTC
