### ISSUE TITLE
Africa/Cairo 2023-4-27 add 1 day, unix value is not correct.

### ISSUE THREAD

**Issue by sirzdy** [moment/moment-timezone#1058] opened 2023-05-06 08:10 UTC
### Environment
```js
console.log({
  moment: moment.version,
  momentTz: moment.tz.version,
  date: (new Date()).toString(),
  intlZone: new Intl.DateTimeFormat().resolvedOptions().timeZone,
});
```
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/17188139/236611901-9b45fa1e-a7fa-4546-a06f-492b00819b4d.png">

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/17188139/236611967-0d3217a1-4acc-48ce-94ff-02163527192e.png">

### Issue description

// 1682632800
new Date('2023-4-28 00:00:00').getTime()/1000

// 1682632800
moment('2023-4-28 00:00:00').unix()

// 1682632800
moment('2023-4-27').add(1,'day').unix()

// 1682629200
moment('2023-4-27').tz('Africa/Cairo').add(1,'day').unix()

// true
moment('2023-4-27').isSame(moment('2023-4-27').tz('Africa/Cairo'))

// true
moment('2023-4-28').isSame(moment('2023-4-28').tz('Africa/Cairo'))

// false
moment('2023-4-27').add(1,'day').isSame(moment('2023-4-27').tz('Africa/Cairo').add(1,'day'))

**Comment by gilmoreorless** [comment] 2023-05-07 09:48
Yep, looks like a bug to me, I suspect it's the same as #409.

What's happening is that DST started for Cairo at `00:00` on April 28, jumping straight to `01:00`. When Moment Timezone is provided that timestamp directly, it correctly calculates the new time:

```js
moment.tz('2023-04-28', 'Africa/Cairo').format();
// '2023-04-28T01:00:00+03:00'
```

But when it's given the day before and adds a day, it incorrectly uses the old hour with the new offset, which is a time that technically doesn't exist:

```js
moment.tz('2023-04-27', 'Africa/Cairo').format();
// '2023-04-27T00:00:00+02:00'
moment.tz('2023-04-27', 'Africa/Cairo').add(1, 'day').format();
// '2023-04-28T00:00:00+03:00'   WRONG, should be 01:00:00
```

I'm going to close this as a duplicate of #409, and you can watch that issue for an update of when the bug is fixed.

**Closed by gilmoreorless** 2023-05-07 09:48 UTC

**Comment by sirzdy** [comment] 2023-05-08 02:56
Thanks a lot!
