### ISSUE TITLE
Incorrect result when parsing time in a timezone

### ISSUE THREAD

**Issue by createthis** [moment/moment-timezone#867] opened 2020-06-19 23:41 UTC
# Repro steps:

```js
import moment from 'moment-timezone';
import tk from 'timekeeper';
tk.freeze(moment('2020-06-19T20:00:00-04:00').toDate());
console.log('now=',moment().format());
const eight_pm_today = moment.tz('8:00 PM', 'h:mm A', 'America/New_York');
console.log('eight_pm_today=',eight_pm_today.format());
```

# Result:
```
now= 2020-06-19T20:00:00-04:00
eight_pm_today= 2020-06-20T20:00:00-04:00
```

# Expected Result:
```
now= 2020-06-19T20:00:00-04:00
eight_pm_today= 2020-06-19T20:00:00-04:00
```

(eight_pm_today is showing as the 20th rather than the 19th)

**Comment by ichernev** [comment] 2022-08-26 13:34
This is a duplicate of #874 (well the other way around, but I already commented on the other one ;-))

**Closed by ichernev** 2022-08-26 13:34 UTC
