### ISSUE TITLE
moment("2019-03-19T10:45:00.000Z").tz("Asia/Singapore" , true) returns "UTC" instead of moment object

### ISSUE THREAD

**Issue by aravindvaideesh** [moment/moment-timezone#733] opened 2019-03-17 15:31 UTC

**Comment by aravindvaideesh** [comment] 2019-03-17 15:33
This does not happen in my local machine but happens inconsistently on production server.

**Comment by adamreisnz** [comment] 2019-04-08 00:44
I also ran into similar issue, where due to data not being present, the timezone string that I was passing into `moment.tz()` was empty, and as a result instead of getting a moment object back, I got a String which caused all sorts of problems.

I know it's convenient to have one method to do all the things, but maybe consider for `.tz()` to _always_ return a moment object for consistency's (and type checking) sake, and implement a different method like `.getTimezone()` to get the actual timezone string.

**Comment by adamreisnz** [comment] 2019-04-08 04:07
At the very least, maybe moment can do a check to count how many arguments have been passed into the `tz()` function, and if this is more than zero, throw an error if the arguments are invalid/undefined, and assume the user wants to have a moment object returned.

Only if `tz()` is called without any arguments should it return the timezone string imo.

**Comment by mj1856** [comment] 2019-04-16 05:00
I cannot reproduce the error reported.  Please verify that you have all data loaded.

At this time, I do not intend to change the interface of moment-timezone.  You may consider [Luxon](https://moment.github.io/luxon/) if you like.

**Comment by adamreisnz** [comment] 2019-04-16 05:29
All due respect, but this has nothing to do with the data that's being loaded. The data is loaded, and the problem is not an error, the problem is that `.tz(input)` doesn't return the expected return value (a moment object) if input is undefined.

This goes against the documentation, because if an argument is provided, the function should return a moment object (regardless of whether or not the input value is undefined or null).

So this is a bug, not a feature request.

**Comment by adamreisnz** [comment] 2019-04-16 09:32
Here's a reproduction. Same function call, same signature, different output:

https://repl.it/repls/PessimisticSlowFile

If you don't want to change the interface of moment-timezone that's fine, but at least make it have consistent output based on the number of arguments someone is putting in.

**Comment by mj1856** [comment] 2019-04-16 15:05
Thanks, I'll look into it further.

**Comment by mj1856** [comment] 2019-04-16 18:04
I think perhaps there's some confusion between `moment.tz(foo)` and `moment().tz(foo)`.

-  `moment.tz(foo)` constructs a `Moment` object. If `foo` is `undefined`, then it defaults to a zone with zero offset and `undefined` for the name - basically the same as if you did `moment.utc()`.  Indeed, `moment.tz(undefined).isUtc()` returns `true`.  This is because moment-timezone layers on top of moment's UTC mode.  This could be better documented, but is not a bug.

- `moment().tz(foo)` constructs a moment in local mode, then converts it to the time zone specified by `foo`.  If `foo` is specified, then it returns a `Moment` object. 

  However, if `foo` is `undefined`, then it is interpreted as `moment().tz()`.  Since the `.tz()` function of a `Moment` object returns the *name* of the time zone, then you get `undefined` since the moment object is in local mode.  This is already documented [here](http://momentjs.com/timezone/docs/#/using-timezones/converting-to-zone/):

  > Without an argument, `moment#tz` returns:
  > - the time zone name assigned to the moment instance or
  > - `undefined` if a time zone has not been set.
  >
  > ```js
  > var m = moment.tz("2013-11-18 11:55", "America/Toronto");
  > m.tz();  // America/Toronto
  > var m = moment.tz("2013-11-18 11:55");
  > m.tz() === undefined;  // true
  > ```

So while I agree with you that this could have been better designed to avoid confusion, and have consistent output of the second form, it is indeed how it was designed.

At this phase of Moment and Moment-Timezone's lifecycle, I'm not pursuing any API changes.  These problems have generally been addressed by [Luxon](https://moment.github.io/luxon/), which should be considered the go-forward plan for Moment users.   (This will be made clearer at some point on the website.)

But thank you very much for your repro and feedback.  👍

**Closed by mj1856** 2019-04-16 18:04 UTC

**Comment by adamreisnz** [comment] 2019-04-16 19:16
Yes, I was aware of this, but the documentation then itself is incorrect.

It reads:

> Without an argument, moment#tz returns:

I am however, passing in an argument with either null value or undefined value.
So either the code should change to actually count the number of arguments passed in, and alter the behaviour accordingly (not just type check for undefined or null), *or* the documentation should read instead something like:

> Without an argument, *or with undefined or null passed in as argument*, moment#tz returns:

I believe the code could be easily adapted to actually do what the documentation suggests, and simply check `arguments.length` to determine what to return.

If the documented behaviour is to return the timezone string when *no* arguments are passed in, then the expected behaviour is to get a moment object *when* arguments are passed in – whether those arguments are null or undefined shouldn't matter.

I will look at migrating to Luxon at some stage.
