### ISSUE TITLE
Incorrect output when adding a day at 00:00 on a DST switch (Brazil)

### ISSUE THREAD

**Issue by dbeinder** [moment/moment-timezone#672] opened 2018-09-19 16:15 UTC
Brazil has their next DST change at midnight:
`console.log(moment.tz("2018-11-03", "America/Sao_Paulo").format())`
`2018-11-03T00:00:00-03:00`
`console.log(moment.tz("2018-11-04", "America/Sao_Paulo").format())`
`2018-11-04T01:00:00-02:00`
`console.log(moment.tz("2018-11-05", "America/Sao_Paulo").format())`
`2018-11-05T00:00:00-02:00`

So on 2018-11-03 we should have 23:58 -> 23:59 -> (next day, offset -2) 01:00 -> 01:01
Adding hours, minutes, etc works:
`console.log(moment.tz("2018-11-03", "America/Sao_Paulo").add(24, "h").format())`
`2018-11-04T01:00:00-02:00`
But adding a day gives the wrong result:
`console.log(moment.tz("2018-11-03", "America/Sao_Paulo").add(1, "d").format())`
`2018-11-03T23:00:00-03:00` (one hour too early)
should be either 2018-11-04T00:00:00-03:00 or 2018-11-04T01:00:00-02:00

Interestingly, when adding a day across the DST boundary, it works just fine as long as the result does not end up directly at the moment of the DST switch:
`console.log(moment.tz("2018-11-03T06:00:00", "America/Sao_Paulo").format())`
`2018-11-03T06:00:00-03:00`
`console.log(moment.tz("2018-11-03T06:00:00", "America/Sao_Paulo").add(1, "d").format())`
`2018-11-04T06:00:00-02:00`

**Comment by johnkoehn** [comment] 2018-09-21 22:32
I've also dealt with this bug.

If you need a work around do moment.tz.setDefault('America/Sao_Paulo')

**Comment by Rhysjc** [comment] 2018-10-18 14:17
Experiencing the same problem

**Comment by Rhysjc** [comment] 2018-10-22 08:34
@lfreneda Nope. Looks like there are tonnes of DST issues in Brazil after they moved the date a couple of times.

**Comment by epimeth** [comment] 2018-10-23 13:56
I think (hope) all that is required, here, is updating the data files.  IANA has a new one as of 2018-10-18.  However, the comment in the file mentions November 4th vs 18th, but literally the only article I can find about this ([here](https://androidcommunity.com/brazils-dst-change-inadvertently-affects-millions-of-android-phones-20181022/)) mentions an angoing issue ***right now***.  Suffice it to say, I am quite confused.

**Comment by epimeth** [comment] 2018-10-23 14:14
I found [another](https://veja.abril.com.br/brasil/relogios-de-celulares-se-adiantam-mas-horario-de-verao-nao-comecou/) article, this time on a Brazilian site en Portuguese... Also, my confusion is settled as to what the correct date is.  Apparently the issue is that they changed the date from a few days ago to the 4th, then again to the 18th, then back to the original change (the 4th)

**Comment by lfreneda** [comment] 2018-10-23 14:22
Just updated to moment-timezone lasted version (0.5.17) and everything is working as expected.

**Comment by mariotsi** [comment] 2018-10-24 21:05
Change of DST cancelled 
https://github.com/moment/moment-timezone/issues/683#issuecomment-432827768

**Comment by garhiggins** [comment] 2018-11-01 00:09
This isn't related the DST move in 2018 - it's an artifact of the fact that the change occurs at midnight. Here's an example from a prior year:
> moment.tz('2017-10-14 00:00:00', 'America/Sao_Paulo').add(1, 'day').format()
```"2017-10-14T23:00:00-03:00"```

I think everyone agrees this is a bug. But one thing I considered to convince myself further that this is unreasonable is that if the DST shift was 30 minutes, or 2 hours, the result would be 23:30 or 22:00. So, the amount of time left before the end of the day depends on a DST shift that still occurs in the future.

**Comment by mj1856** [comment] 2019-04-16 05:20
Duplicate of #409.  Tracking there.  Thanks.

**Closed by mj1856** 2019-04-16 05:20 UTC
