### ISSUE TITLE
"moment().add(1,'d')" doesn't behave as expected  around timezone changes

### ISSUE THREAD

**Issue by jodevsa** [moment/moment-timezone#676] opened 2018-10-05 15:59 UTC
Hi there,

After reviewing an [issue](https://github.com/kelektiv/node-cron/issues/381) in [Cron](https://github.com/kelektiv/node-cron/); a  library that utilizes moment-timezone for time zone support. We were able to trace it back to the  unexpected behavior occurring from reading date.days() value after triggering date.add(1,'d')` 

Steps to reproduce: 
```
const moment = require('moment-timezone');
const date= moment.tz(new Date("Sat Nov 03 2018 00:00:00 GMT-0300"),"America/Sao_Paulo")
console.log(date.days());
console.log(date.toString()); // outputs: Sat Nov 03 2018 00:00:00 GMT-0300
date.add(1,'d');
console.log(date.days())
console.log(date.toString())  // outputs: Sat Nov 03 2018 23:00:00 GMT-0300 but should be  Sat Nov 04 2018 00:00:00 GMT-0200


```

**Comment by jodevsa** [comment] 2018-10-05 19:06
I understand that this might be due to timezone changes but event date.day() remain unchanged after the add

**Comment by mj1856** [comment] 2019-04-16 05:22
Duplicate of #409.  Tracking there.  Thanks.

**Closed by mj1856** 2019-04-16 05:22 UTC
