### ISSUE TITLE
Issuing Adding Day Across DST Boundary

### ISSUE THREAD

**Issue by joshwils82** [moment/moment-timezone#727] opened 2019-02-14 14:45 UTC
If I add 1 day and the result hits a DST boundary that should cause a spring forward, it instead subtracts 1 hour.  This does not happen if I add 1 second, 1 hour, or even 24 hours.  It seems to be specific to 1 day.

Here is the jsfiddle showing the issue: https://jsfiddle.net/q81gsr0L/

Here is some sample code and output that demonstrates the issue:

```
'use strict'

const moment = require('moment-timezone')

console.log(moment.tz("2018-11-03 23:59:59", "America/Sao_Paulo").add(1, 's').format())
console.log(moment.tz("2018-11-03 23:00:00", "America/Sao_Paulo").add(1, 'h').format())
console.log(moment.tz("2018-11-03 00:00:00", "America/Sao_Paulo").add(24, 'h').format())
console.log(moment.tz("2018-11-03 00:00:00", "America/Sao_Paulo").add(1, 'd').format())
```
```
2018-11-04T01:00:00-02:00
2018-11-04T01:00:00-02:00
2018-11-04T01:00:00-02:00
2018-11-03T23:00:00-03:00
```

You will notice the last value should match the others but does not.

**Comment by mj1856** [comment] 2019-04-16 05:21
Duplicate of #409.  Tracking there.  Thanks.

**Closed by mj1856** 2019-04-16 05:21 UTC
