### ISSUE TITLE
Moment wrong after setting default timezone

### ISSUE THREAD

**Issue by SudoPlz** [moment/moment-timezone#513] opened 2017-07-21 21:14 UTC
Hey there @timrwood

Check this fiddle http://jsfiddle.net/sudoplz/zgfbd2mf/4/

Before setting the default timezone everything seems to be working fine, but after it's been set all hell breaks loose.

Here's the code:
```
var beforeTz = moment('1500673235723', 'x').format('h:mma DD/MM/YYYY');
moment.tz.setDefault('Europe/Athens')
var afterTz = moment('1500673235723', 'x').format('h:mma DD/MM/YYYY');

alert(`\nBEFORE: ${beforeTz}\nAFTER: ${afterTz}`);
```
<img width="177" alt="screen shot 2017-07-22 at 00 14 27" src="https://user-images.githubusercontent.com/3070948/28482801-c29365a2-6e72-11e7-8df8-e865069c68bf.png">

I've tried with various versions.
It seems to be working when using `moment-timezone: 0.3.1` but if I go above that it just fails to read that timestamp.

which today are:

```
"moment": "2.18.1",
"moment-timezone": "0.5.13",
```

Any idea why that's happening?
ty

**Comment by mj1856** [comment] 2017-07-22 00:48
Hi!  This is a duplicate of a known bug, #347.  Workaround: Pass the timestamp as a number rather than parsing it with `x`.

Also note that Tim has moved on to other things.
https://medium.com/@timrwood/moment-endof-term-522d8965689

Cheers!
-Matt

**Closed by mj1856** 2017-07-22 00:48 UTC
