### ISSUE TITLE
Do not log error when requiring moment-timezone multiple times in Node

### ISSUE THREAD

**Issue by mderazon** [moment/moment-timezone#231] opened 2015-07-07 10:26 UTC
In Node it is quite common to require a module in multiple places

Right now if I require moment-timezone in multiple places I am getting 

```
Moment Timezone 0.4.0 was already loaded with data from 2015d
```

That comes from [this line](https://github.com/moment/moment-timezone/blob/f71d6ea7537ae280518f7ac345beaba1209ab48e/moment-timezone.js#L23) (#212 )

This shouldn't be logged as an error and just clutters the server logs.
If anything, it should be a warning but in Node env it shouldn't be printed at all IMO

**Comment by mj1856** [comment] 2015-07-09 17:55
Except that it can actually cause errors when the same time zone is defined more than once.

@timrwood - Perhaps we need to do more than just log an error in order to accommodate node.js scenarios?

**Comment by mderazon** [comment] 2015-07-09 18:37
AFAIK node has a caching mechanism when requiring modules so that it shouldn't load module more than once

https://nodejs.org/api/modules.html#modules_caching

**Comment by mj1856** [comment] 2015-07-09 22:16
If that's the case, then why would you be seeing the error message in your logs?  It should only appear then if it wasn't already loaded in the cache, right?

**Comment by mj1856** [comment] 2015-07-09 22:18
Perhaps you could supply a GIST with a minimal example that gives the error?

**Comment by mderazon** [comment] 2015-07-10 12:50
I can't seem to be able to reproduce this.

I have a setup where I require moment-tz couple of times in my app and I also require a second module that requires moment-tz. When I try to replicate it I don't get the error message. 

It looks like some quirk in npm that i'm not aware of, I will try to investigate it further and understand why it's being loaded twice in my app

**Comment by mderazon** [comment] 2015-07-10 14:19
@mj1856 problem solved.

I had couple of old dependencies in my node_modules folder. After cleaning it up and restarting the module seems to be loading only once.

Sorry for the noise, 

Thanks for your help !

**Comment by mj1856** [comment] 2015-07-10 16:55
No problem, and glad to hear you got it working! :smile:

**Comment by FredKSchott** [comment] 2015-07-10 22:12
We're still having this problem. We use moment-timezone inside of our app, but the ORM sequelize also uses the library internally. So we get this error.

What exact problems come from two different apps requiring moment? Can that problem still occur when a moment-timezone is loaded inside both the application and a dependency?

**Comment by mj1856** [comment] 2015-07-11 00:20
@timrwood  - Is there a better way to handle this?  Loading into two different instances should be ok. It's only loading twice in the same instance that is problematic.  Maybe just make the loading idempotent instead of throwing an error?

**Comment by jonahkirangi** [comment] 2016-01-31 07:03
I seem to be running into the same issue as @FredKSchott. Any discussion regarding two different apps requiring moment? 

`Moment Timezone 0.3.1 was already loaded with data from 2015a`

**Comment by poislagarde** [comment] 2016-02-01 02:18
Same here, any suggestions?

**Comment by antoniopironti** [comment] 2016-02-02 11:34
+1

Making the loading idempotent as suggested by would be ideal imo.

**Comment by johnRivs** [comment] 2016-02-17 14:09
I went from 0.3.1 to 0.5.0. I'm requiring `moment-timezone` literally in a single file. Removed `node_modules`, did `npm cache clean`, then installed 0.5.0. I get `Moment Timezone 0.3.1 was already loaded with data from 2015a`.

How do I solve this?

**Comment by Braynid** [comment] 2016-02-22 19:26
I'm getting this as well. Sequelize has moment-timezone as a dependency and almost certainly that causes the issue.

**Comment by jhohlfeld** [comment] 2016-02-23 11:09
+1

> Making the loading idempotent as suggested by @mj1856 and @antoniopironti would be ideal imo.

**Comment by loris** [comment] 2016-02-24 11:09
Same issue here, let’s say I have an app using `moment`, and dependencies using `moment-timezone` (like Sequelize or Agenda), it displays `Moment Timezone 0.3.1 was already loaded with data from 2015a`

**Comment by rickhub** [comment] 2016-03-01 14:19
I'm able to reproduct this problem if i install the package rschmukler/agenda, because it depends on moment-timezone@0.5.0 and cron@0.1.0 -> which depends on moment-timezone@0.3.1.

**Comment by igormucsicska-planorama** [comment] 2016-03-03 14:36
+1

**Comment by djtregear** [comment] 2016-03-03 21:56
Hi I'm also getting "Moment Timezone 0.3.1 was already loaded with data from 2015a" when I require('agenda') from rschmukler/agenda.
It doesn't appear to be causing me any issues, just a little annoying.

**Comment by timrwood** [comment] 2016-03-04 01:20
I've started work on #298, breaking moment-timezone into smaller es6 modules, which should make this problem easier to address.

The main problem is that the data loaded in an older version does not match the data loaded in a newer version.

I suppose we could compare the `moment-timezone` version and the `tzdb` versions and use the newest one.

**Comment by ee99ee** [comment] 2016-04-07 23:36
Also getting this...

**Comment by niftylettuce** [comment] 2016-05-16 04:29
still not fixed?

**Comment by loris** [comment] 2016-05-27 13:41
It’s been almost a year, maybe we could remove the `console.log` polluting logs in the meantime?

**Comment by avingochea** [comment] 2016-05-28 17:16
+1

**Comment by stephengardner** [comment] 2016-06-23 13:44
Another month

**Comment by dawsonc623** [comment] 2016-07-05 15:02
This is a pretty big pain for me, as the logging library used on an e-commerce project I am tasked with fixing suffers from this issue, so none of the logs have dates or times. It is insanely difficult for me to track down which logs occurred when to match logs to observed behavior in the system at the time they were observed.

At this time, I am reduced to sitting and waiting for the error to happen again to see exactly which logs are written, which means I am literally waiting for this company to lose more money. Can this be prioritized in any way? If you have not completed a fix, but have completed your reorganization, can it be placed in a branch so that the community (myself included) can try to complete the fix ourselves without stepping on your work?

**Comment by loris** [comment] 2016-07-07 08:43
Seriously, just remove the useless `console.log` line. I can’t even do it in a fork, `moment-timezone` is a dep of other libraries i’m using. Here’s what i have to do right now, this is ridiculous
```
const oldConsoleLog = console.log;
console.log = () => {};
import Agenda from 'agenda';
console.log = oldConsoleLog;
```

**Comment by jonnywyatt** [comment] 2016-07-07 15:14
This is polluting our logs, could you change from 'error' to 'warning' please?

**Comment by ronenteva** [comment] 2016-07-22 03:47
+1

**Comment by damienleroux** [comment] 2016-08-10 09:04
+1

**Comment by dimd13** [comment] 2016-09-12 05:21
+1

**Comment by Left47** [comment] 2016-09-13 23:38
+1

**Comment by raabbajam** [comment] 2016-09-17 00:36
+1

**Comment by nmaggioni** [comment] 2016-10-13 17:54
+1

**Comment by aletorrado** [comment] 2016-11-24 21:45
+1 !!!!

**Comment by ptitdje45** [comment] 2016-11-25 14:34
+1

**Comment by rollrodrig** [comment] 2016-12-09 16:00
Hi. i saw why this error is log.
When i load
moment.js
moment-timezone.min.js
moment-timezone-with-data.min
print the error.
Also with
moment.js
moment-timezone.min.js
moment-timezone-with-data.min.js
moment-timezone-with-data-2010-2020.min.js

To prevent the log error i only loaded
moment.js
moment-timezone-with-data.min.js

And now the error is gone.

Greetings.

**Comment by basicdays** [comment] 2016-12-13 15:46
I think the problem is NPM 3's deduplication and `moment-timezone`'s monkey patching of the `moment` package. I'd have to test this, but I think the following causes multiple different `moment-timezone` packages to attempt to monkey patch the same `moment` module.

```
my-project/
|- package.json
|- node_modules/
   |- moment/ (v2.6.0)
   |- moment-timezone/ (v0.5.1)
   |- do-stuff/
      |- package.json (can use the same moment version but a different moment-timezone)
      |- moment-timezone/ (v0.4.1)
```

So when `do-stuff` requires `moment-timezone`, it attempts to monkey patch the root `moment` package. And when `moment-timezone` is required in `my-project`, it attempts to monkey patch `moment` with a newer `moment-timezone` package even though the `do-stuff` library already monkey patched it with an older `moment-timezone`.

I'd have to think of some ways that could be done to solve this, but this isn't an easy fix. If the projects were merged, the problem would probably go away though...

**Comment by dilame** [comment] 2016-12-14 17:11
This is just horrible.

```
├── moment-timezone@0.5.10 
└─┬ sails-hook-cron@2.2.0
  └─┬ cron@1.1.0
    └── moment-timezone@0.3.1 
```
my app just had broken because of this. I installed new package `sails-hook-cron`, that uses moment-timezone@0.3.1  , and other part of my application no longer able to call `moment.tz.guess()`.
First i thought it is nodejs issue. But now i see its smth wrong with moment-timezone. Fix it, please.

**Comment by maggiepint** [comment] 2016-12-23 18:38
The console.log has been removed and released 0.5.11

**Closed** 2017-01-05 18:22 UTC
Labels: enhancement

**Comment by nitrocode** [comment] 2017-11-14 23:08
I just saw this from `pm2-logrotate`'s error logs

> Moment Timezone 0.5.14 was already loaded with data from 2017c

**Comment by Dushusir** [comment] 2018-05-25 08:49
now,it's 

> Moment Timezone 0.5.14 was already loaded with data from 2017c.

what should i do?

load js:
    <script src="plugins/moment.min.js"></script>
    <script src="plugins/moment-timezone.min.js"></script>
    <script src="plugins/moment-timezone-with-data.js"></script>
    <script src="plugins/moment-msdate.js"></script>
