### ISSUE TITLE
Timezones matching the current system timezone

### ISSUE THREAD

**Issue by emmanuel-vasseur** [moment/moment-timezone#55] opened 2014-01-25 15:52 UTC
Hello,

I need to know which timezones match the current system timezone, in order to do some date format manipulation on server side.
Few apis exists for this feature, and it is not a simple because in javascript we need to deal with timezone offset and test multiple dates.

However this thread on stackoverflow talks about this feature using moment timezone datas : http://stackoverflow.com/questions/19420582/detect-the-id-of-the-current-user-timezone-using-moment-js

I could simply used this peace of code but it can be certainly improve and why not include in moment timezone library.

The person that post this peace of code test the current date, the dates 4 and 8 months later and the same three dates five years before.
Is it a good strategy ? Can I improve it to have closer timezones matching ?

I need this feature so I can improve this peace of code with your advices and, if you're agreed, publish it in your repository.

**Comment by ivanakimov** [comment] 2015-01-08 01:22
+1

**Comment by kashifshamaz21** [comment] 2015-02-14 17:10
This feature request is a duplicate of #138, and i'm going to close this in favour of the other one as it has more discussions around the actual implementations.

**Closed by kashifshamaz21** 2015-02-14 17:10 UTC
Labels: duplicate, planned

**Comment by timrwood** [comment] 2015-05-13 15:37
I opened a PR for this at #220.

**Comment by timrwood** [comment] 2015-12-28 16:52
This has been released in `moment-timezone@0.5.0` as `moment.tz.guess()`.

**Comment by ivanakimov** [comment] 2015-12-28 16:53
Nice :+1:
