### ISSUE TITLE
Can't parse MMM (month format) datetimes.

### ISSUE THREAD

**Issue by SudoPlz** [moment/moment-timezone#550] opened 2017-10-22 18:21 UTC
Hi there,

after of banging my head on the wall for quite a while, I figured that I can't do something like:
import momentTz from 'moment-timezone';

`momentTz('Jan_2018', 'MMM_YYYY');`

When I do that I get `Unhandled JS Exception: Attempted to assign to readonly property.`
<img width="331" alt="screen shot 2017-10-22 at 21 17 23" src="https://user-images.githubusercontent.com/3070948/31864909-6bff4cde-b76e-11e7-9e2c-43f8c366f488.png">

If I switch the debugger on, I get the following error:

`Can't add property _monthsShortRegex, object is not extensible
ExceptionsManager.js:65 Unhandled JS Exception: Can't add property _monthsShortRegex, object is not extensible`

<img width="340" alt="screen shot 2017-10-22 at 21 19 12" src="https://user-images.githubusercontent.com/3070948/31864929-aac01250-b76e-11e7-8e0d-c854a30200fa.png">

which is pretty similar to https://github.com/moment/moment/issues/3118

I found that if I change my code to: 

`momentTz('January_2018', 'MMMM_YYYY');`

everything **works**.
It just seems to not like the 3 M's.. (`MMM`), and it only happens with `moment-timezone`, not with `moment`.

I'm on:

    "moment": "2.19.1",
    "moment-timezone": "0.5.13",

Thanks

**Comment by mj1856** [comment] 2017-11-01 20:04
I cannot reproduce this.  Can you please create a jsFiddle or similar to demonstrate?  Thanks.

**Comment by mj1856** [comment] 2017-11-02 18:27
Also, please try in 0.5.14.

**Comment by SudoPlz** [comment] 2017-11-02 18:59
I'll try to create a jsfiddle

**Comment by SudoPlz** [comment] 2017-11-02 19:11
Ah, I can't reproduce in jsfiddle. I was running that code on a react-native project that uses babel though. I have literally no idea what could have caused it. It's still a problem if I use 3 Ms, and it is the weirdest thing ever.

**Comment by mj1856** [comment] 2017-11-10 21:06
Ok, I'm closing this for now.  If you can reproduce then we can reopen.  Thanks.

**Closed by mj1856** 2017-11-10 21:06 UTC
Labels: Troubleshooting
