### ISSUE TITLE
America/Sao_Paulo DST issue in 2019

### ISSUE THREAD

**Issue by xcomanche** [moment/moment-timezone#728] opened 2019-02-14 18:05 UTC
I saw few other issues open for DST at Sao Paulo. But looks like all of them related to 2018 DST. 
```
const date = moment('2019-11-01').tz('America/Sao_Paulo').startOf('day')
date.format()
"2019-11-01T00:00:00-03:00"

date.add(1, 'day').format()
"2019-11-02T00:00:00-03:00"
date.add(1, 'day').format()
"2019-11-02T23:00:00-03:00"

moment.version
"2.24.0"

moment.tz.version
"0.5.23"
```

**Comment by uvuwolverine** [comment] 2019-04-15 14:07
We've also seen this problem in our calendar, only for this time zone. Have you had any luck with a fix?

**Comment by mj1856** [comment] 2019-04-16 05:21
Duplicate of #409.  Tracking there.  Thanks.

**Closed by mj1856** 2019-04-16 05:21 UTC
