### ISSUE TITLE
No timezone detected on Ubuntu Linux

### ISSUE THREAD

**Issue by falko** [moment/moment-timezone#503] opened 2017-06-13 06:58 UTC
When I go to http://momentjs.com/timezone/ no timezone is displayed. I'm running Ubuntu 16.04.2 LTS and tried Firefox 53.0.3 (64-bits), Chromium 58.0.3029.110 and Opera 45.0. If I do the same in a Windows VM, it properly displays 'Europe/Berlin 08:57 am CEST'

    $ date
    Di 13. Jun 08:34:53 CEST 2017

If I try the following JavaScript code it detects the offset correctly:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_gettimezoneoffset

**Comment by falko** [comment] 2017-06-14 09:47
$ more /etc/timezone
    Europe/Berlin

**Comment by mj1856** [comment] 2017-06-26 16:05
What precisely do you mean by "no timezone is displayed"?   The moment-timezone website give a map of the time zones of the world.  What you get back is related to where you place your mouse, not what is on your machine.

We have a function `moment.tz.guess()` that you could call for that, but is that what you're doing?

**Comment by falko** [comment] 2017-06-30 07:57
The page http://momentjs.com/timezone/ displays a timezone even without placing the mouse on the map. My understanding is, that this is the time zone detected from my browser. However, on my Linux system, the detection doesn't seem to work.

**Comment by gilmoreorless** [comment] 2022-09-16 05:42
Time zone guessing issues like this often come down to the underlying data in the browser, which changes over time. I'm closing this off for now, but if the problem is still happening, feel free to re-open the issue.

**Closed by gilmoreorless** 2022-09-16 05:42 UTC
Labels: Troubleshooting
